### ISSUE TITLE
Inquiry Regarding the Publication Date of the "PNP" Paper on Human Motion Capture

### ISSUE THREAD

**Issue by SlimeVRX** [Xinyu-Yi/PNP#1]
Hello Author's PNP Team,

I hope this message finds you well. I'm reaching out with great anticipation regarding your upcoming paper titled "PNP," which I understand focuses on a real-time human motion capture system based on 6 IMUs, upgrading PIP through the incorporation of non-inertial forces. The summary of the paper has significantly piqued my interest, as it aligns closely with my areas of research and passion.

Your team's innovative approach to enhancing human motion capture by integrating non-inertial forces into the PIP framework is particularly intriguing to me. I believe this advancement could offer profound implications for the field and pave the way for new research directions and applications.

I am eager to delve into the details of your methodologies, findings, and the potential impacts of your work on the broader research community. Could you please share any available information regarding the expected publication date of the PNP paper? I am keen on incorporating the insights from your research into my study as soon as possible.

Thank you very much for your time and consideration. I am looking forward to the publication of the PNP paper and am excited about the new knowledge and perspectives it will bring to the field.

Best regards,
Tin Nguyen

**Comment by Xinyu-Yi** [comment]
Thanks for your interest in our work! Currently, the paper has not been published yet. We expect it to be released in approximately one month. In the meantime, we are considering creating a webpage where we can showcase some related videos and additional content.

**Comment by Xinyu-Yi** [comment]
I think in this work we have a large improvement over PIP, and also superior to sony mocopi in our qualitative comparison.

**Comment by SlimeVRX** [comment]
Thank you for the update. I'm eagerly anticipating the PNP paper. Please inform me here when there's an update. Many thanks!

**Comment by Xinyu-Yi** [comment]
Hi, I am still modifying the paper, but I have uploaded the website. I think the paper can be made public at the end of this month.
