### ISSUE TITLE
咨询几个论文和训练相关问题

### ISSUE THREAD

**Issue by StayYouth1993** [Xinyu-Yi/PNP#6]
1. 论文中公式6提到的基于能量优化，这块公式是不是有误？三者单位不同，按照论文的公式，最终优化会趋向于加速度接近于0，因为加速度那一项是没有 dt 的，实际优化的时候，如果保持三者单位一致，最终会接近真实数据，如果按照论文所示，使用QP优化，会导致加速度趋近于0。

> 关于这个点，另外想咨询的是，实际操作的时候，m选取多大？因为m变大会导致最终的QP展开非常复杂，你们是单个迭代的还是分段迭代的？其中 Vi 和 Vi+1 是根据数据集计算来的还是根据a_ij 累积加和计算来的。

2. 训练的序列长度大概多长？另外，在 amass 上训练多少个epoch，在imu数据集（dip-imu & totalcapture）finetune多少个epoch。
3. 最终演示的效果，有采用自己搜集的数据进行训练么？自己采集的数据训练的label是包含所有的么？如果采用了自己采集的数据，方便告知采集的数据长度，以及采集了多少组数据么？并且finetue了多少个epoch？
4. 对于dip-imu数据，我发现有的有异常噪声，这里有做处理么？比如序列最开始的时候，部分数据存在40左右的加速度，但是dip-imu的数据最开始应该是apose。
5. 关于佩戴点位，有测试佩戴在膝盖和佩戴在脚踝的区别么？这两个地方加速度会有很明显的差异，特别是在预测脚底是否静止的label时，差异会很明显，但是不清楚对于预测大腿朝向是否有明显区别。

**Comment by Xinyu-Yi** [comment]
1. 我们具体的实现还比较复杂，我当时写的稿子您可以参考这个https://xinyu-yi.github.io/PNP/images/math_imusyn.jpg

我记得具体的思路就是平滑样条，对加速度来说想让加加速度尽可能小，对角速度来说想让角加速度尽可能小。这个解起来确实比较慢，我建议实际换成gaussian filter，调一下参数效果可以比较接近

**Comment by Xinyu-Yi** [comment]
2. 序列长度随着训练是递增的，训练200个epoch。我记得每10个epoch finetune一次
3. 没有用自己的数据集，我们自己的livedemo数据没有gt，只能看结果
4. 合成的时候微分就需要丢掉开头结尾几帧，可能就没问题了
5. 公开数据集都在膝盖上，我们也想戴到脚上，但现在没有这样的真实数据用于训练。

**Comment by StayYouth1993** [comment]
非常感谢耐心详细的回复！！！
